### ISSUE TITLE
Girls Bedroom

### ISSUE THREAD

**Issue by amglovier** [jglovier/house-upkeep#48]
- [ ] Lightbulb out

**Comment by woodall** [comment]
I'm very intrigued by this whole setup going on here. How can I learn more? Please :bulb: me

**Comment by jglovier** [comment]
Hi @woodall :wave:! We just use this repo to track progress on household tasks. It's one extra way to test out using GitHub Issues for project management, and it's pretty handy.

Also, pretty sad that neither me nor @amglovier has gotten around to changing this bulb in nearly 3 months lol. :laughing:

**Comment by woodall** [comment]
Got tired of them stealing your flashlights?
