### ISSUE TITLE
Weekend Warriors - Apr 2015 edition

### ISSUE THREAD

**Issue by jglovier** [jglovier/house-upkeep#51]
@amglovier and I have some free time to do household stuff this weekend. Here's a TODO list of things we could try to accomplish:

- [x] Take Talain's stuff to basement from Garage
- [x] Sweep and mop basement
- [x] Take weight bench to basement and assemble
- [x] Put together basketball hoop
- [x] Install ceiling fans in living room
- [x] Install ceiling fan in bedroom
- [x] Install darkening curtains in bedroom
- [x] Hang new mirror in guest bedroom
- [x] Hang new mirror in downstairs bathroom

cc #50

**Comment by amglovier** [comment]
- [ ] Clean out garage--move everything out, sweep, tidy up, etc
- [ ] Epoxi garage floor
- [ ]  Finish garage mural 
- [ ] Buy a hose real that can be cemented in the ground near AC unit
- [ ] New mulch in oval bed and tree beds; turn over mulch in long bed
- [ ] Paint bathroom with paint that is smudge proof!!

**Comment by jglovier** [comment]
@amglovier Lets move those additional tasks out to a new issue for a new planned time.
